### ISSUE TITLE
Sensitive information is leaked

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#47]
https://github.com/linero-tech/module-306-a-team/blob/52805fe15b3b1538ce6345f3d150e90411424969/app/google-services.json#L1-L11

This file should have been added to the gitignore. The reason is because it contains sensitive information about the Google Project. Since the repository where this project is located is public, anyone could access this file and use your Firebase project. 

Once the project is done, I recommend deleting the Firebase project so that this file is no longer valid. 

For next time, make sure to not make this file publicly available.

**Comment by erikscc** [comment]
fixed
