### ISSUE TITLE
Repeated File

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#51]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/Backends/GetQuestions.kt#L1-L17

This file a complete duplication of the file `RetrofitClient`. Keep only one of them and erase the other. 

Note: Pick the file that has the most appropriate naming.

**Comment by erikscc** [comment]
The two file have different instances and using them to two different calls , I can't use the request without one of them.

**Comment by hlinero** [comment]
Look at the files. They are exactly the same, you do not need two.

**Comment by hlinero** [comment]
To solve this issue, you need to also address this one: https://github.com/linero-tech/module-306-a-team/issues/52

You need to work together to get it done. Both issues are related.

**Comment by erikscc** [comment]
fixed
