### ISSUE TITLE
Method is too long

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#56]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/CreateAccount.kt#L42-L93

Half the code of this class is contained inside a single function.

Functions that are too big (like this one) are hard to understand, maintain, and improve. You have to break this function into smaller functions so that it is easier to understand what it is doing.

**Comment by erikscc** [comment]
done
