### ISSUE TITLE
Excessive use of !! operator

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#59]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/CreateAccount.kt#L66

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/CreateAccount.kt#L77

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/LoginPage.kt#L64

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/LoginPage.kt#L72

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L48

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L55

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L58

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L68

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L78

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L104

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L58

Although there are cases where using the `!!` is fine or necessary, it is not encourage to use it and you should avoid it as much as possible. 

The more you use it, the more likely your app is to have a `NullPointerException` and thus crash.

Instead of using the `!!` operator, I want you to use one of the null safety features of Kotlin link the elvis operator (`?:`) or the `let.` operator to access values.

**Comment by beshe94** [comment]
throw task.exception!! and  getQuestions(response.body()!!.token) i could not change it becaouse whenever i do it it show error. But the rest is done
