### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#62]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L78-L86

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L56-L59

Your code only handles the case if the task is successful. What happens if the task is not successful? Based on your code, nothing happens, which is not appropriate. At the very least, you shall let the user know that something went wrong and that the operation that you were trying to do failed.

**Comment by erikscc** [comment]
done
