### ISSUE TITLE
Improve name of variables and method

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#63]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L28

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L50

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ResultActivity.kt#L68

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L22

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L361

Why use the prefixes `my` or `the`? They are redundant and add no value. Please remove those prefixes

----------------------

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L355

Why use `mustHaveColor` and not just `color`?  The variable name `mustHaveColor` does not add any value. If your function is setting the color, if you are calling the function in the first place it means that you intend to add the given color. 

----------------------

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L21

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L27-L28

- `allRandom`, what random? what all?
- It is unclear what `regexQuot` or `regexUpper` are supposed to do

-------------------

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L323

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/LoginPage.kt#L37

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/LoginPage.kt#L87

All the methods here are unclear. For example:
- `start()` start what?
-  `clickListener()`, Are you setting a click listener? Are you creating a click listener? 

Method names shall express an clear intent of what they are supposed to do.

**Comment by beshe94** [comment]
Done
