### ISSUE TITLE
Remove duplication in CreateAccount and LoginActivity

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#65]
There is significant duplication between the function `authentication()` in `LoginPage` and `accountCreation()` in `CreateAccount`.

This duplication not only makes your code harder to maintain but also to understand. I want you to extract the common parts of those two methods into its own class and reduce the amount of duplication

**Comment by Musadrammeh** [comment]
N_ot all the way resolved, but almost
