### ISSUE TITLE
Unused Listeners

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#66]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L50-L53

Why have listener if they are not being used for anything? If you are not planning on doing anything inside these listeners, erase them.

**Comment by beshe94** [comment]
done
