### ISSUE TITLE
Refactor Methods: Reduce method size and remove duplication within method

### ISSUE THREAD

**Issue by hlinero** [linero-tech/module-306-a-team#68]
https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L45

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L102

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L161

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/GameActivity.kt#L232

https://github.com/linero-tech/module-306-a-team/blob/8b4c97d8b1e99a0517aa1ba1e7b663a06362fa03/app/src/main/java/se/linerotech/quizkampen/ProfilePage.kt#L45

All the methods I have mentioned above need to me improved. In the following ways:
- They are too long and hard to understand. You must extract some functionality out of it and create new methods to simplify them
- Inside some of those method you have a lot of duplication. That is, you are doing pretty much the same thing over and over again. Create methods and to try to reuse your code. Do not copy/paste

**Comment by erikscc** [comment]
private fun selectItem -Done

**Comment by erikscc** [comment]
private fun selectItem -Done

**Comment by erikscc** [comment]
private fun firstStart

**Comment by erikscc** [comment]
private fun questionPreview

**Comment by erikscc** [comment]
private fun displayAnswers

**Comment by erikscc** [comment]
binding.changeInfo.setOnClickListener{
